# Generated by Django 5.2.1 on 2026-02-04 20:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Secuencia',
                'verbose_name_plural': 'Secuencias',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_code', models.PositiveIntegerField(editable=False, unique=True)),
                ('serial', models.CharField(max_length=80, unique=True)),
                ('patente', models.CharField(max_length=15, unique=True)),
                ('nombre_referencial', models.CharField(blank=True, max_length=80, null=True)),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=60)),
                ('anio', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_compra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('compra_financiada', models.BooleanField(default=False)),
                ('credito_hasta', models.DateField(blank=True, null=True)),
                ('kilometraje_actual', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted_logical', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.PositiveIntegerField(editable=False, unique=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('color', models.CharField(default='blue', help_text='Nombre simple (ej: blue, green, red, yellow, gray). Solo para el badge.', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Status de vehículo',
                'verbose_name_plural': 'Status de vehículos',
                'ordering': ['status_code'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('seguro', 'Seguro'), ('permiso', 'Permiso de circulación'), ('revision', 'Revisión técnica'), ('otro', 'Otro')], max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('renovado_en', models.DateField(blank=True, null=True)),
                ('vence_en', models.DateField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='flota/documentos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='flota.vehicle')),
            ],
            options={
                'verbose_name': 'Documento de vehículo',
                'verbose_name_plural': 'Documentos de vehículo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleOdometerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_km', models.PositiveIntegerField()),
                ('new_km', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('rendicion', 'Rendición'), ('servicio', 'Servicio'), ('combustible', 'Combustible'), ('otro', 'Otro')], default='manual', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odometer_events', to='flota.vehicle')),
            ],
            options={
                'verbose_name': 'Evento de kilometraje',
                'verbose_name_plural': 'Eventos de kilometraje',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='flota.vehiclestatus'),
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_assignments', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='flota.vehicle')),
            ],
            options={
                'verbose_name': 'Asignación de vehículo',
                'verbose_name_plural': 'Asignaciones de vehículo',
                'ordering': ['-assigned_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('vehicle',), name='uniq_active_assignment_per_vehicle')],
            },
        ),
    ]
