# Generated by Django 5.2.1 on 2026-02-04 21:56

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='compra_financiada',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='credito_hasta',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_deleted_logical',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='nombre_referencial',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='valor_compra',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fecha_fin_credito',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fecha_permiso_circulacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fecha_ultima_revision_tecnica',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_movement_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='monto_compra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='nombre_fantasia',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tipo_compra',
            field=models.CharField(choices=[('contado', 'Al contado'), ('credito', 'Crédito'), ('leasing', 'Leasing')], default='contado', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_code',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicleodometerevent',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('servicio', 'Servicio'), ('combustible', 'Combustible'), ('rendicion', 'Rendición'), ('otro', 'Otro')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclestatus',
            name='color',
            field=models.CharField(default='blue', help_text='Nombre simple (blue, green, red, yellow, gray). Para badge Tailwind.', max_length=30),
        ),
        migrations.AlterField(
            model_name='vehiclestatus',
            name='status_code',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='VehicleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('service_type', models.CharField(choices=[('combustible', 'Combustible'), ('aceite', 'Cambio de aceite'), ('neumaticos', 'Cambio de neumáticos'), ('revision_tecnica', 'Revisión técnica'), ('permiso_circulacion', 'Permiso de circulación'), ('otro', 'Otro')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('service_date', models.DateField(default=datetime.date.today)),
                ('service_time', models.TimeField(blank=True, null=True)),
                ('kilometraje_declarado', models.PositiveIntegerField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='flota.vehicle')),
            ],
            options={
                'verbose_name': 'Servicio de vehículo',
                'verbose_name_plural': 'Servicios de vehículos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='VehicleDocument',
        ),
    ]
