# Generated by Django 5.2.1 on 2026-02-05 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0002_remove_vehicle_anio_remove_vehicle_compra_financiada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('interval_km', models.PositiveIntegerField(blank=True, help_text='Frecuencia en KM (ej: 5000).', null=True)),
                ('interval_days', models.PositiveIntegerField(blank=True, help_text='Frecuencia en días (ej: 180).', null=True)),
                ('alert_before_km', models.PositiveIntegerField(default=100, help_text='Avisar cuando falten X KM.')),
                ('alert_before_days', models.PositiveIntegerField(default=7, help_text='Avisar cuando falten X días.')),
                ('color', models.CharField(default='blue', help_text='Nombre simple (blue, green, red, yellow, gray). Para badge Tailwind.', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de servicio',
                'verbose_name_plural': 'Tipos de servicio',
                'ordering': ['type_code', 'name'],
            },
        ),
        migrations.AddField(
            model_name='vehicleservice',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicleservice',
            name='next_due_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicleservice',
            name='service_type_obj',
            field=models.ForeignKey(blank=True, help_text='Tipo configurable (para alarmas y frecuencias).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='flota.vehicleservicetype'),
        ),
        migrations.AddIndex(
            model_name='vehicleservice',
            index=models.Index(fields=['vehicle', 'created_at'], name='flota_vehic_vehicle_1f32b0_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleservice',
            index=models.Index(fields=['vehicle', 'service_date'], name='flota_vehic_vehicle_28fe12_idx'),
        ),
    ]
