# Generated by Django 5.2.1 on 2026-02-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0003_vehicleservicetype_vehicleservice_next_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleservicetype',
            name='alert_before_days_steps',
            field=models.CharField(blank=True, default='', help_text='Avisos por días separados por coma. Ej: 10,7,1', max_length=120),
        ),
        migrations.AddField(
            model_name='vehicleservicetype',
            name='alert_before_km_steps',
            field=models.CharField(blank=True, default='', help_text='Avisos por KM separados por coma. Ej: 1000,500,100', max_length=120),
        ),
        migrations.AddField(
            model_name='vehicleservicetype',
            name='notify_on_overdue',
            field=models.BooleanField(default=True, help_text='Si está activo, también avisará cuando el servicio ya esté vencido.'),
        ),
    ]
