# Generated by Django 5.2.1 on 2026-02-28 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0004_vehicleservicetype_alert_before_days_steps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('include_assigned_driver', models.BooleanField(default=True, help_text='Si está activo, se incluirá el correo del chofer asignado (si existe email).')),
                ('extra_emails_to', models.CharField(blank=True, default='', help_text='Correos adicionales (TO) separados por coma.', max_length=500)),
                ('extra_emails_cc', models.CharField(blank=True, default='', help_text='Correos adicionales (CC) separados por coma.', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='flota.vehicle')),
            ],
            options={
                'verbose_name': 'Notificación de flota',
                'verbose_name_plural': 'Notificaciones de flota',
            },
        ),
    ]
