# Generated by Django 5.2.1 on 2026-02-28 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0005_vehiclenotificationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlotaCronDiarioEjecutado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'Cron diario ejecutado (Flota)',
                'verbose_name_plural': 'Cron diarios ejecutados (Flota)',
                'constraints': [models.UniqueConstraint(fields=('nombre', 'fecha'), name='uniq_flota_cron_por_dia')],
            },
        ),
        migrations.CreateModel(
            name='FlotaAlertaEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('pre_km', 'Pre KM'), ('pre_days', 'Pre días'), ('overdue_km', 'Vencido KM'), ('overdue_days', 'Vencido días')], max_length=20)),
                ('threshold', models.PositiveIntegerField(default=0)),
                ('sent_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_base', to='flota.vehicleservice')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_sent', to='flota.vehicleservicetype')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_sent', to='flota.vehicle')),
            ],
            options={
                'verbose_name': 'Alerta enviada (Flota)',
                'verbose_name_plural': 'Alertas enviadas (Flota)',
                'indexes': [models.Index(fields=['vehicle', 'service_type', 'base_service', 'mode'], name='flota_flota_vehicle_b3abb2_idx'), models.Index(fields=['sent_on'], name='flota_flota_sent_on_fd0ec3_idx')],
                'constraints': [models.UniqueConstraint(fields=('vehicle', 'service_type', 'base_service', 'mode', 'threshold'), name='uniq_flota_pre_alert_once'), models.UniqueConstraint(fields=('vehicle', 'service_type', 'base_service', 'mode', 'sent_on'), name='uniq_flota_overdue_daily')],
            },
        ),
    ]
