# Generated by Django 5.2.1 on 2025-12-12 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operaciones', '0016_requisito_norm_cleanup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Correo')], max_length=20)),
                ('tipo', models.CharField(choices=[('servicio_asignado', 'Servicio asignado'), ('servicio_aprobado_supervisor', 'Servicio aprobado por supervisor'), ('servicio_rechazado_supervisor', 'Servicio rechazado por supervisor'), ('contrato_generado', 'Contrato generado'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('titulo', models.CharField(blank=True, default='', max_length=255)),
                ('mensaje', models.TextField()),
                ('extra', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('error', 'Error')], db_index=True, default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, null=True)),
                ('du', models.CharField(blank=True, default='', help_text='DU relacionado, para buscar rápido aunque el servicio ya no exista.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_generadas', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='operaciones.serviciocotizado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['canal', 'tipo', 'status'], name='notificacio_canal_c000ee_idx'), models.Index(fields=['du'], name='notificacio_du_2d662b_idx')],
            },
        ),
    ]
