# Generated by Django 5.2.1 on 2025-12-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Log de notificación', 'verbose_name_plural': 'Logs de notificaciones'},
        ),
    ]
