# Generated by Django 5.2.1 on 2025-12-15 14:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Identificador interno, ej: 'mis_liquidaciones'", unique=True)),
                ('nombre', models.CharField(help_text='Nombre amigable del intent, visible en admin.', max_length=100)),
                ('descripcion', models.TextField(blank=True, default='', help_text='Descripción de qué hace este intent.')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('tecnico', 'Técnico'), ('admin', 'Administrativo'), ('finanzas', 'Finanzas'), ('rrhh', 'RRHH')], default='tecnico', help_text='Ámbito principal donde aplica este intent.', max_length=20)),
                ('activo', models.BooleanField(default=True, help_text='Si está desactivado, el motor no lo usará.')),
                ('requiere_revision_humana', models.BooleanField(default=False, help_text='Si está activo, las respuestas de este intent se marcan para revisión en la consola de entrenamiento.')),
            ],
            options={
                'verbose_name': 'Intent del bot',
                'verbose_name_plural': 'Intents del bot',
            },
        ),
        migrations.CreateModel(
            name='BotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, help_text='Chat ID de Telegram.', max_length=64)),
                ('contexto', models.CharField(default='tecnico', help_text='Contexto actual del bot para este chat.', max_length=20)),
                ('estado', models.CharField(blank=True, default='', help_text='Identificador del estado actual del flujo conversacional.', max_length=100)),
                ('datos_contexto', models.JSONField(blank=True, help_text='Datos temporales para completar flujos (rendiciones, filtros, etc.).', null=True)),
                ('activa', models.BooleanField(default=True, help_text='Para pausar sesiones si es necesario.')),
                ('ultima_interaccion', models.DateTimeField(default=django.utils.timezone.now, help_text='Última vez que el usuario habló con el bot.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ultimo_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_ultimo_intent', to='bot_gz.botintent')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario interno vinculado a este chat (si se pudo mapear).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión del bot',
                'verbose_name_plural': 'Sesiones del bot',
            },
        ),
        migrations.CreateModel(
            name='BotMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(db_index=True, help_text='Chat ID de Telegram (duplicado por comodidad).', max_length=64)),
                ('direccion', models.CharField(choices=[('in', 'Usuario → Bot'), ('out', 'Bot → Usuario')], max_length=3)),
                ('texto', models.TextField(help_text='Texto del mensaje enviado o recibido.')),
                ('confianza', models.FloatField(blank=True, help_text='Score de confianza del clasificador (si aplica).', null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('fallback', 'Fallback (no entendido)'), ('error', 'Error interno')], default='ok', help_text='Resultado interno del procesamiento de este mensaje.', max_length=10)),
                ('marcar_para_entrenamiento', models.BooleanField(default=False, help_text='Si está activo, este mensaje aparece en la vista de entrenamiento.')),
                ('meta', models.JSONField(blank=True, help_text='Metadata adicional (parámetros interpretados, errores, etc.).', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('intent_corregido', models.ForeignKey(blank=True, help_text='Intent corregido manualmente para entrenamiento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_intent_corregido', to='bot_gz.botintent')),
                ('intent_detectado', models.ForeignKey(blank=True, help_text='Intent que el motor cree que corresponde.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_intent_detectado', to='bot_gz.botintent')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario interno vinculado (si lo hay).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_mensajes', to=settings.AUTH_USER_MODEL)),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='bot_gz.botsession')),
            ],
            options={
                'verbose_name': 'Mensaje del bot',
                'verbose_name_plural': 'Mensajes del bot',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='BotTrainingExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(help_text='Frase tal como la escribiría un usuario.', max_length=512)),
                ('locale', models.CharField(default='es', help_text="Idioma / variante. Ej: 'es', 'es-CL'.", max_length=10)),
                ('activo', models.BooleanField(default=True, help_text='Si está desactivado, no se usa para entrenamiento.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_training_creados', to=settings.AUTH_USER_MODEL)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_examples', to='bot_gz.botintent')),
            ],
            options={
                'verbose_name': 'Ejemplo de entrenamiento',
                'verbose_name_plural': 'Ejemplos de entrenamiento',
            },
        ),
        migrations.AddIndex(
            model_name='botsession',
            index=models.Index(fields=['chat_id'], name='bot_gz_bots_chat_id_d4e989_idx'),
        ),
        migrations.AddIndex(
            model_name='botsession',
            index=models.Index(fields=['usuario', 'activa'], name='bot_gz_bots_usuario_146c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='botmessagelog',
            index=models.Index(fields=['chat_id', 'creado_en'], name='bot_gz_botm_chat_id_79034c_idx'),
        ),
        migrations.AddIndex(
            model_name='botmessagelog',
            index=models.Index(fields=['status'], name='bot_gz_botm_status_55f60e_idx'),
        ),
        migrations.AddIndex(
            model_name='botmessagelog',
            index=models.Index(fields=['marcar_para_entrenamiento'], name='bot_gz_botm_marcar__6bb35a_idx'),
        ),
    ]
