# Generated by Django 5.2.1 on 2026-07-07 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_gz', '0001_initial'),
        ('operaciones', '0016_requisito_norm_cleanup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaClimaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('chat_id', models.CharField(blank=True, default='', max_length=80)),
                ('id_claro', models.CharField(blank=True, default='', max_length=100)),
                ('id_new', models.CharField(blank=True, default='', max_length=100)),
                ('nombre_sitio', models.CharField(blank=True, default='', max_length=255)),
                ('direccion', models.TextField(blank=True, default='')),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('temperatura_c', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sensacion_c', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('viento_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('indice_uv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nivel_uv', models.CharField(blank=True, default='', max_length=40)),
                ('factor_solar_recomendado', models.CharField(blank=True, default='', max_length=40)),
                ('radiacion_wm2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('prob_lluvia', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('condicion', models.CharField(blank=True, default='', max_length=120)),
                ('fuente', models.CharField(blank=True, default='open-meteo', max_length=80)),
                ('estado_envio', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('error', 'Error'), ('sin_telegram', 'Sin Telegram'), ('sin_asignacion', 'Sin asignación'), ('sin_ubicacion', 'Sin ubicación')], default='pendiente', max_length=30)),
                ('error_envio', models.TextField(blank=True, default='')),
                ('mensaje_enviado', models.TextField(blank=True, default='')),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_clima_bot', to='operaciones.serviciocotizado')),
                ('sitio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_clima_bot', to='operaciones.sitiomovil')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_clima_bot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-creado_en'],
                'indexes': [models.Index(fields=['trabajador', 'fecha'], name='bot_gz_aler_trabaja_383b37_idx'), models.Index(fields=['estado_envio', 'fecha'], name='bot_gz_aler_estado__d8c553_idx')],
            },
        ),
    ]
