# Generated by Django 5.2.1 on 2026-07-08 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_gz', '0002_alertaclimadiaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotRutaDireccionFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('oficina', 'Oficina'), ('bodega', 'Bodega'), ('companero', 'Compañero'), ('otro', 'Otro')], db_index=True, max_length=30)),
                ('nombre', models.CharField(blank=True, default='', help_text='Nombre opcional. Ej: Casa, Oficina, Compañero Juan.', max_length=120)),
                ('direccion', models.TextField(blank=True, default='', help_text='Dirección escrita por el usuario.')),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_ruta_direcciones_frecuentes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección frecuente de ruta',
                'verbose_name_plural': 'Direcciones frecuentes de ruta',
                'indexes': [models.Index(fields=['usuario', 'tipo', 'activo'], name='bot_gz_botr_usuario_e052ad_idx')],
            },
        ),
    ]
