# Generated by Django 5.2.1 on 2026-02-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_cartolamovimiento_rut_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartolamovimiento',
            name='fecha_transaccion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha real del movimiento'),
        ),
    ]
