# Generated by Django 5.2.1 on 2026-02-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0014_cartolamovimiento_aprobado_finanzas_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartolamovimiento',
            name='en_historial',
            field=models.BooleanField(default=False),
        ),
    ]
