# Generated by Django 5.2.1 on 2026-02-03 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_cartolamovimiento_en_historial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartolamovimiento',
            name='historial_enviado_el',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartolamovimiento',
            name='historial_enviado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartola_historial_enviados', to=settings.AUTH_USER_MODEL),
        ),
    ]
