# Generated by Django 5.2.1 on 2026-02-22 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0016_cartolamovimiento_historial_enviado_el_and_more'),
        ('flota', '0004_vehicleservicetype_alert_before_days_steps_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartolamovimiento',
            options={'ordering': ['-fecha'], 'verbose_name': 'Cartola Movimiento', 'verbose_name_plural': 'Cartola Movimientos'},
        ),
        migrations.AddField(
            model_name='cartolamovimiento',
            name='fecha_servicio_flota',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha servicio flota'),
        ),
        migrations.AddField(
            model_name='cartolamovimiento',
            name='hora_servicio_flota',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora servicio flota'),
        ),
        migrations.AddField(
            model_name='cartolamovimiento',
            name='kilometraje_servicio_flota',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraje servicio flota'),
        ),
        migrations.AddField(
            model_name='cartolamovimiento',
            name='servicio_flota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendiciones_origen', to='flota.vehicleservice', verbose_name='Servicio creado en Flota'),
        ),
        migrations.AddField(
            model_name='cartolamovimiento',
            name='tipo_servicio_flota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendiciones_cartola', to='flota.vehicleservicetype', verbose_name='Tipo de servicio (Flota)'),
        ),
        migrations.AddField(
            model_name='cartolamovimiento',
            name='tipo_servicio_flota_snapshot',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre tipo servicio (snapshot)'),
        ),
        migrations.AddField(
            model_name='cartolamovimiento',
            name='vehiculo_flota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendiciones_cartola', to='flota.vehicle', verbose_name='Vehículo (Flota)'),
        ),
        migrations.AddIndex(
            model_name='cartolamovimiento',
            index=models.Index(fields=['status'], name='facturacion_status_c5ce36_idx'),
        ),
        migrations.AddIndex(
            model_name='cartolamovimiento',
            index=models.Index(fields=['fecha'], name='facturacion_fecha_46f8b6_idx'),
        ),
        migrations.AddIndex(
            model_name='cartolamovimiento',
            index=models.Index(fields=['fecha_transaccion'], name='facturacion_fecha_t_ca2ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='cartolamovimiento',
            index=models.Index(fields=['usuario', 'status'], name='facturacion_usuario_4ea1a4_idx'),
        ),
        migrations.AddIndex(
            model_name='cartolamovimiento',
            index=models.Index(fields=['vehiculo_flota'], name='facturacion_vehicul_cf3490_idx'),
        ),
        migrations.AddIndex(
            model_name='cartolamovimiento',
            index=models.Index(fields=['servicio_flota'], name='facturacion_servici_ff3dd3_idx'),
        ),
    ]
