# Generated by Django 5.2.1 on 2026-02-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0017_alter_cartolamovimiento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipogasto',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Gasto', 'verbose_name_plural': 'Tipos de Gasto'},
        ),
        migrations.AddField(
            model_name='tipogasto',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
    ]
