# Generated by Django 5.2.1 on 2025-12-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0034_solicitudadelanto_puede_editar_rrhh'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratotrabajo',
            name='notificado_por_vencer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contratotrabajo',
            name='notificado_vencido',
            field=models.BooleanField(default=False),
        ),
    ]
