# Generated by Django 5.2.1 on 2025-12-11 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0035_contratotrabajo_notificado_por_vencer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratotrabajo',
            name='notificado_por_vencer',
        ),
        migrations.RemoveField(
            model_name='contratotrabajo',
            name='notificado_vencido',
        ),
    ]
