# Generated by Django 5.2.1 on 2025-12-12 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0036_remove_contratotrabajo_notificado_por_vencer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronDiarioEjecutado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('ejecutado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('nombre', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='ContratoAlertaEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_termino', models.DateField()),
                ('dias_antes', models.PositiveIntegerField()),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_enviadas', to='rrhh.contratotrabajo')),
            ],
            options={
                'unique_together': {('contrato', 'fecha_termino', 'dias_antes')},
            },
        ),
    ]
