# Generated by Django 5.2.1 on 2025-12-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0037_crondiarioejecutado_contratoalertaenviada'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratotrabajo',
            name='notificar_vencimiento',
            field=models.BooleanField(default=True, help_text='Si está desmarcado, no se enviarán correos de alerta para este contrato.'),
        ),
        migrations.AlterField(
            model_name='contratoalertaenviada',
            name='dias_antes',
            field=models.IntegerField(),
        ),
    ]
