# Generated by Django 5.2.1 on 2026-06-12 19:45

import django.db.models.deletion
from django.db import migrations, models


def crear_tipo_contrato_por_defecto(apps, schema_editor):
    TipoDocumentoLaboral = apps.get_model("rrhh", "TipoDocumentoLaboral")
    ContratoTrabajo = apps.get_model("rrhh", "ContratoTrabajo")

    tipo_contrato, creado = TipoDocumentoLaboral.objects.get_or_create(
        nombre="Contrato de trabajo",
        defaults={
            "afecta_vigencia": True,
            "cierra_relacion_laboral": False,
            "genera_alerta_vencimiento": True,
            "activo": True,
        },
    )

    ContratoTrabajo.objects.filter(tipo_documento_laboral__isnull=True).update(
        tipo_documento_laboral_id=tipo_contrato.id,
        activo=True,
    )


def reversa_segura_tipo_contrato_por_defecto(apps, schema_editor):
    """
    Reversa segura:
    No eliminamos el tipo ni tocamos contratos existentes para evitar pérdida
    de información en producción.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0038_contratotrabajo_notificar_vencimiento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDocumentoLaboral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "afecta_vigencia",
                    models.BooleanField(
                        default=True,
                        help_text="Si está activo, este tipo de documento afecta la vigencia laboral del trabajador.",
                    ),
                ),
                (
                    "cierra_relacion_laboral",
                    models.BooleanField(
                        default=False,
                        help_text="Si está activo, este tipo de documento cierra la relación laboral. Ejemplo: finiquito.",
                    ),
                ),
                (
                    "genera_alerta_vencimiento",
                    models.BooleanField(
                        default=True,
                        help_text="Si está activo, los documentos de este tipo pueden generar alertas de vencimiento.",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tipo de documento laboral",
                "verbose_name_plural": "Tipos de documentos laborales",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="contratotrabajo",
            name="activo",
            field=models.BooleanField(
                default=True,
                help_text="Indica si este documento laboral está activo para efectos de vigencia y alertas.",
            ),
        ),
        migrations.AddField(
            model_name="contratotrabajo",
            name="cerrado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Documento laboral que cerró este documento. Ejemplo: un finiquito.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_cerrados",
                to="rrhh.contratotrabajo",
            ),
        ),
        migrations.AddField(
            model_name="contratotrabajo",
            name="motivo_cierre",
            field=models.CharField(
                blank=True,
                help_text="Motivo por el cual este documento dejó de estar activo. Ejemplo: reemplazado por anexo, cerrado por finiquito.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contratotrabajo",
            name="observacion",
            field=models.TextField(
                blank=True,
                help_text="Observación interna asociada al documento laboral.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contratotrabajo",
            name="reemplazado_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Documento laboral que reemplazó a este documento. Ejemplo: un nuevo contrato o anexo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_reemplazados",
                to="rrhh.contratotrabajo",
            ),
        ),
        migrations.AddField(
            model_name="contratotrabajo",
            name="tipo_documento_laboral",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo de documento laboral: contrato, anexo, finiquito, acuerdo, condiciones de arriendo u otro.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contratos_trabajo",
                to="rrhh.tipodocumentolaboral",
                verbose_name="Tipo de documento laboral",
            ),
        ),
        migrations.RunPython(
            crear_tipo_contrato_por_defecto,
            reversa_segura_tipo_contrato_por_defecto,
        ),
    ]
