# Generated by Django 5.2.1 on 2026-03-13 11:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevencionDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('scope', models.CharField(choices=[('empresa', 'Empresa'), ('trabajador', 'Trabajador'), ('ambos', 'Ambos')], default='trabajador', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrevencionNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('include_worker', models.BooleanField(default=True, help_text='Si el documento es de trabajador, incluir el correo del/los trabajadores (si tienen email).')),
                ('extra_to', models.TextField(blank=True, default='', help_text='Correos TO separados por coma.')),
                ('extra_cc', models.TextField(blank=True, default='', help_text='Correos CC separados por coma.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prevención - Configuración de notificaciones',
                'verbose_name_plural': 'Prevención - Configuración de notificaciones',
            },
        ),
        migrations.CreateModel(
            name='PrevencionCronDiarioEjecutado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('fecha', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('nombre', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='PrevencionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('empresa', 'Empresa'), ('trabajador', 'Trabajador'), ('ambos', 'Ambos')], max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('file', models.FileField(max_length=1024, upload_to='prevencion/documentos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('no_requiere_vencimiento', models.BooleanField(default=False, help_text='Si está marcado, el documento no tiene caducidad y no entra en el cron.')),
                ('notify_enabled', models.BooleanField(default=True)),
                ('current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prevencion_docs_created', to=settings.AUTH_USER_MODEL)),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='prevencion.prevenciondocument')),
                ('workers', models.ManyToManyField(blank=True, help_text='Aplica si el documento es de trabajador o ambos.', related_name='prevencion_documents', to=settings.AUTH_USER_MODEL)),
                ('doc_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='prevencion.prevenciondocumenttype')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PrevencionAlertaEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=20)),
                ('threshold', models.IntegerField(default=0)),
                ('sent_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_sent', to='prevencion.prevenciondocument')),
            ],
            options={
                'indexes': [models.Index(fields=['mode', 'threshold', 'sent_on'], name='prevencion__mode_5e1140_idx'), models.Index(fields=['doc', 'mode', 'threshold'], name='prevencion__doc_id_a8f9fb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='prevenciondocument',
            index=models.Index(fields=['current', 'notify_enabled'], name='prevencion__current_33e289_idx'),
        ),
        migrations.AddIndex(
            model_name='prevenciondocument',
            index=models.Index(fields=['scope', 'current'], name='prevencion__scope_4e9286_idx'),
        ),
        migrations.AddIndex(
            model_name='prevenciondocument',
            index=models.Index(fields=['expiry_date'], name='prevencion__expiry__e8a8c0_idx'),
        ),
    ]
