# Generated by Django 5.2.1 on 2026-03-14 02:16

import django.core.validators
import operaciones.storage_backends
import prevencion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prevenciondocument',
            name='file',
            field=models.FileField(max_length=1024, storage=operaciones.storage_backends.GZWasabiStorage(), upload_to=prevencion.models.upload_to_prevencion_document, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx'])]),
        ),
    ]
