# Generated by Django 5.2.1 on 2026-03-14 03:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prevencion', '0002_alter_prevenciondocument_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prevenciondocument',
            name='apply_to_all_workers',
            field=models.BooleanField(
                default=False,
                help_text='Si está marcado, el documento aplica a todos los trabajadores actuales y futuros.',
            ),
        ),
        migrations.AddIndex(
            model_name='prevenciondocument',
            index=models.Index(
                fields=['apply_to_all_workers'],
                name='prevencion__apply_t_9da7c0_idx',
            ),
        ),
    ]