# Generated by Django 5.2.1 on 2026-08-18 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitioplanificado',
            name='activo_en_mes',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='sitioplanificado',
            name='alerta_motor',
            field=models.TextField(blank=True, default='', help_text='Resumen de alertas o advertencias calculadas por el motor para este sitio.'),
        ),
        migrations.CreateModel(
            name='BatchPlanificacionSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(db_index=True, help_text='Lunes de la semana objetivo.')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('propuesto', 'Propuesto'), ('gestion_permisos', 'Gestión de permisos'), ('listo_planificar', 'Listo para planificar'), ('planificado', 'Planificado'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], db_index=True, default='borrador', max_length=30)),
                ('nombre', models.CharField(blank=True, default='', max_length=150)),
                ('objetivo_sitios', models.PositiveIntegerField(default=40, help_text='Cantidad objetivo aproximada para el batch.')),
                ('generado_por_motor', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_planificacion_actualizados', to=settings.AUTH_USER_MODEL)),
                ('configuracion_semana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='planificacion.configuracionsemana')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_planificacion_creados', to=settings.AUTH_USER_MODEL)),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='planificacion.planificacionmensual')),
            ],
            options={
                'ordering': ['fecha_inicio', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ImportacionAsignacionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(blank=True, default='', max_length=255)),
                ('nombre_hoja', models.CharField(blank=True, default='', max_length=255)),
                ('columna_id_detectada', models.CharField(blank=True, default='', max_length=255)),
                ('estado', models.CharField(choices=[('preview', 'Preview'), ('aplicada', 'Aplicada'), ('cancelada', 'Cancelada'), ('error', 'Error')], db_index=True, default='preview', max_length=20)),
                ('total_filas', models.PositiveIntegerField(default=0)),
                ('total_ids_detectados', models.PositiveIntegerField(default=0)),
                ('ids_unicos', models.PositiveIntegerField(default=0)),
                ('ids_repetidos', models.PositiveIntegerField(default=0)),
                ('vinculados', models.PositiveIntegerField(default=0)),
                ('no_encontrados', models.PositiveIntegerField(default=0)),
                ('ya_existentes_mes', models.PositiveIntegerField(default=0)),
                ('creados', models.PositiveIntegerField(default=0)),
                ('errores', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aplicado_en', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='importaciones_asignacion_planificacion', to=settings.AUTH_USER_MODEL)),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importaciones_asignacion', to='planificacion.planificacionmensual')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='sitioplanificado',
            name='importacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitios_creados', to='planificacion.importacionasignacionmensual'),
        ),
        migrations.CreateModel(
            name='SitioBatchSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('candidato', 'Candidato'), ('seleccionado', 'Seleccionado'), ('gestion_permiso', 'Gestión de permiso'), ('disponible', 'Disponible'), ('rechazado', 'Rechazado'), ('sin_respuesta', 'Sin respuesta'), ('excluido', 'Excluido'), ('reemplazado', 'Reemplazado'), ('confirmado', 'Confirmado')], db_index=True, default='candidato', max_length=30)),
                ('origen', models.CharField(choices=[('motor', 'Motor'), ('manual', 'Manual'), ('prioridad', 'Prioridad'), ('reemplazo', 'Reemplazo')], db_index=True, default='manual', max_length=20)),
                ('puntaje_motor', models.DecimalField(blank=True, decimal_places=2, help_text='Puntaje calculado por el motor para recomendar este sitio dentro del batch.', max_digits=7, null=True)),
                ('motivo_recomendacion', models.TextField(blank=True, default='')),
                ('motivo_exclusion', models.TextField(blank=True, default='')),
                ('agregado_manualmente', models.BooleanField(default=False)),
                ('bloqueado_en_batch', models.BooleanField(default=False, help_text='Evita que futuras recalculaciones automáticas eliminen el sitio de este batch.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('agregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitios_batch_agregados', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitios', to='planificacion.batchplanificacionsemanal')),
                ('sitio_planificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_batch', to='planificacion.sitioplanificado')),
            ],
            options={
                'ordering': ['-puntaje_motor', 'sitio_planificado__sitio__id_claro'],
            },
        ),
        migrations.AddIndex(
            model_name='batchplanificacionsemanal',
            index=models.Index(fields=['planificacion', 'estado'], name='planificaci_planifi_349e5d_idx'),
        ),
        migrations.AddIndex(
            model_name='batchplanificacionsemanal',
            index=models.Index(fields=['fecha_inicio', 'estado'], name='planificaci_fecha_i_d743c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='batchplanificacionsemanal',
            constraint=models.UniqueConstraint(fields=('planificacion', 'fecha_inicio'), name='uq_batch_semana_planificacion'),
        ),
        migrations.AddIndex(
            model_name='importacionasignacionmensual',
            index=models.Index(fields=['planificacion', 'estado'], name='planificaci_planifi_41d69f_idx'),
        ),
        migrations.AddIndex(
            model_name='sitiobatchsemanal',
            index=models.Index(fields=['batch', 'estado'], name='planificaci_batch_i_7a2a07_idx'),
        ),
        migrations.AddIndex(
            model_name='sitiobatchsemanal',
            index=models.Index(fields=['origen', 'estado'], name='planificaci_origen_30d3e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='sitiobatchsemanal',
            constraint=models.UniqueConstraint(fields=('batch', 'sitio_planificado'), name='uq_sitio_batch_semanal'),
        ),
    ]
