# Generated by Django 5.2.1 on 2026-08-18 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0002_sitioplanificado_activo_en_mes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitiobatchsemanal',
            name='es_reserva',
            field=models.BooleanField(db_index=True, default=False, help_text='Indica que el sitio pertenece al batch como alternativa o respaldo y no como sitio principal.'),
        ),
        migrations.CreateModel(
            name='DisponibilidadCuadrillaSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuadrilla', models.CharField(choices=[('cuadrilla_1', 'Cuadrilla 1'), ('cuadrilla_2', 'Cuadrilla 2'), ('cuadrilla_3', 'Cuadrilla 3')], db_index=True, max_length=30)),
                ('modalidad', models.CharField(choices=[('lunes_viernes', 'Lunes a viernes'), ('lunes_sabado', 'Lunes a sábado')], db_index=True, default='lunes_viernes', max_length=30)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('capacidad_diaria_objetivo', models.PositiveSmallIntegerField(default=3, help_text='Cantidad objetivo de sitios que esta cuadrilla puede ejecutar por día. Es una referencia nominal y no reemplaza el análisis real de rutas, distancias y restricciones.')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disponibilidades_cuadrilla_semana_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('configuracion_semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_cuadrillas', to='planificacion.configuracionsemana')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disponibilidades_cuadrilla_semana_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disponibilidad de cuadrilla semanal',
                'verbose_name_plural': 'Disponibilidades de cuadrillas semanales',
                'ordering': ['configuracion_semana__fecha_inicio', 'cuadrilla'],
                'indexes': [models.Index(fields=['configuracion_semana', 'activa'], name='planificaci_configu_b81d76_idx'), models.Index(fields=['cuadrilla', 'modalidad'], name='planificaci_cuadril_f4e085_idx')],
                'constraints': [models.UniqueConstraint(fields=('configuracion_semana', 'cuadrilla'), name='uq_disponibilidad_cuadrilla_semana')],
            },
        ),
    ]
