# Generated by Django 5.2.1 on 2026-08-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0003_sitiobatchsemanal_es_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitiobatchsemanal',
            name='cluster_codigo',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identificador del cluster geográfico asignado por el motor dentro del batch semanal.', max_length=50),
        ),
    ]
