# Generated by Django 5.2.1 on 2026-08-18 16:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0004_sitiobatchsemanal_cluster_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadcuadrillasemana',
            name='base_latitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitud del punto de salida de la cuadrilla.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='disponibilidadcuadrillasemana',
            name='base_longitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitud del punto de salida de la cuadrilla.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='disponibilidadcuadrillasemana',
            name='base_nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre descriptivo del punto desde donde inicia y termina la jornada de esta cuadrilla.', max_length=150),
        ),
        migrations.AddField(
            model_name='disponibilidadcuadrillasemana',
            name='minutos_jornada_objetivo',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cantidad de minutos disponibles para una jornada normal. El motor considera dentro de este tiempo: ida desde la base, trabajo en sitio, traslados entre sitios y regreso a la base.', null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadcuadrillasemana',
            name='minutos_trabajo_sitio_estimado',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Duración operacional estimada por sitio para esta cuadrilla durante esta semana. Si queda vacío, el motor utilizará su valor general de referencia.', null=True),
        ),
        migrations.AlterField(
            model_name='disponibilidadcuadrillasemana',
            name='capacidad_diaria_objetivo',
            field=models.PositiveSmallIntegerField(default=3, help_text='Cantidad objetivo nominal de sitios que esta cuadrilla podría ejecutar por día. Es solo una referencia. El motor definitivo decide 1, 2 o 3 sitios según tiempos de traslado, trabajo y regreso.'),
        ),
    ]
