# Generated by Django 5.2.1 on 2026-08-18 17:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0005_disponibilidadcuadrillasemana_base_latitud_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadcuadrillasemana',
            name='base_latitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Override opcional de latitud para esta semana.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='disponibilidadcuadrillasemana',
            name='base_longitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Override opcional de longitud para esta semana.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='disponibilidadcuadrillasemana',
            name='base_nombre',
            field=models.CharField(blank=True, default='', help_text='Override opcional del nombre de la base para esta semana. Vacío = usar base habitual de la cuadrilla.', max_length=150),
        ),
        migrations.AlterField(
            model_name='disponibilidadcuadrillasemana',
            name='capacidad_diaria_objetivo',
            field=models.PositiveSmallIntegerField(default=3, help_text='Referencia nominal de sitios diarios. El motor real decide 1, 2 o 3 según tiempos.'),
        ),
        migrations.AlterField(
            model_name='disponibilidadcuadrillasemana',
            name='minutos_jornada_objetivo',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Override semanal de duración de jornada. Vacío = usar valor habitual de la cuadrilla.', null=True),
        ),
        migrations.AlterField(
            model_name='disponibilidadcuadrillasemana',
            name='minutos_trabajo_sitio_estimado',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Override semanal del tiempo estimado por sitio. Vacío = usar valor habitual de la cuadrilla.', null=True),
        ),
        migrations.CreateModel(
            name='CuadrillaOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Código interno único. Ejemplo: cuadrilla_1, cuadrilla_2, cuadrilla_4.', max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('orden', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Orden visual de la cuadrilla dentro de planificación.')),
                ('tipo_vehiculo', models.CharField(blank=True, default='', help_text='Ejemplo: 4x4, Partner, camioneta, furgón.', max_length=100)),
                ('permite_urbano', models.BooleanField(default=True)),
                ('permite_rural', models.BooleanField(default=False)),
                ('direccion_base', models.CharField(blank=True, default='', max_length=255)),
                ('base_nombre', models.CharField(blank=True, default='', help_text='Nombre corto de la base. Ejemplo: Base Ñuñoa, Base Santiago Centro.', max_length=150)),
                ('base_latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('base_longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('minutos_jornada_default', models.PositiveSmallIntegerField(default=540, help_text='Duración nominal de la jornada en minutos. 540 = 9 horas.')),
                ('minutos_trabajo_sitio_default', models.PositiveSmallIntegerField(default=165, help_text='Tiempo estimado inicial por sitio. 165 = 2 horas 45 minutos.')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuadrillas_operativas_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuadrillas_operativas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuadrilla operativa',
                'verbose_name_plural': 'Cuadrillas operativas',
                'ordering': ['orden', 'nombre', 'id'],
            },
        ),
        migrations.AddField(
            model_name='disponibilidadcuadrillasemana',
            name='cuadrilla_operativa',
            field=models.ForeignKey(blank=True, help_text='Cuadrilla maestra asociada. Es el campo que utilizará el nuevo motor.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disponibilidades_semanales', to='planificacion.cuadrillaoperativa'),
        ),
        migrations.AddIndex(
            model_name='disponibilidadcuadrillasemana',
            index=models.Index(fields=['cuadrilla_operativa', 'activa'], name='planificaci_cuadril_9ad174_idx'),
        ),
        migrations.AddConstraint(
            model_name='disponibilidadcuadrillasemana',
            constraint=models.UniqueConstraint(fields=('configuracion_semana', 'cuadrilla_operativa'), name='uq_disponibilidad_cuadrilla_operativa_semana'),
        ),
        migrations.AddIndex(
            model_name='cuadrillaoperativa',
            index=models.Index(fields=['activa', 'orden'], name='planificaci_activa_b23921_idx'),
        ),
        migrations.AddIndex(
            model_name='cuadrillaoperativa',
            index=models.Index(fields=['permite_rural', 'activa'], name='planificaci_permite_c61be7_idx'),
        ),
    ]
