# Generated by Django 5.2.1 on 2026-08-19 19:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0007_migrar_disponibilidad_a_cuadrilla_operativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponibilidadcuadrillasemana',
            options={'ordering': ['configuracion_semana__fecha_inicio', 'cuadrilla_operativa__orden', 'cuadrilla_operativa__nombre', 'cuadrilla', 'id'], 'verbose_name': 'Disponibilidad de cuadrilla semanal', 'verbose_name_plural': 'Disponibilidades de cuadrillas semanales'},
        ),
        migrations.AlterField(
            model_name='disponibilidadcuadrillasemana',
            name='base_latitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Override opcional de latitud para esta semana. Vacío = utilizar la latitud habitual de la cuadrilla.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='disponibilidadcuadrillasemana',
            name='base_longitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Override opcional de longitud para esta semana. Vacío = utilizar la longitud habitual de la cuadrilla.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='disponibilidadcuadrillasemana',
            name='base_nombre',
            field=models.CharField(blank=True, default='', help_text='Override opcional del nombre de la base para esta semana. Vacío = utilizar la base habitual de la cuadrilla.', max_length=150),
        ),
        migrations.AlterField(
            model_name='disponibilidadcuadrillasemana',
            name='capacidad_diaria_objetivo',
            field=models.PositiveSmallIntegerField(default=3, help_text='Referencia nominal de sitios diarios. No obliga al motor a ejecutar esa cantidad. El cálculo operacional puede determinar 1, 2 o 3 según desplazamientos, jornada y tiempo por sitio.'),
        ),
        migrations.AlterField(
            model_name='disponibilidadcuadrillasemana',
            name='cuadrilla_operativa',
            field=models.ForeignKey(blank=True, help_text='Cuadrilla maestra asociada a esta disponibilidad semanal. Los nuevos registros deben utilizar este campo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disponibilidades_semanales', to='planificacion.cuadrillaoperativa'),
        ),
        migrations.AlterField(
            model_name='disponibilidadcuadrillasemana',
            name='minutos_jornada_objetivo',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Override semanal de duración de jornada. Vacío = utilizar el valor habitual de la cuadrilla.', null=True),
        ),
        migrations.AlterField(
            model_name='disponibilidadcuadrillasemana',
            name='minutos_trabajo_sitio_estimado',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Override semanal del tiempo estimado por sitio. Vacío = utilizar el valor habitual de la cuadrilla.', null=True),
        ),
        migrations.CreateModel(
            name='SalidaPlanificacionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden visual de la salida dentro de la fecha. Normalmente una cuadrilla tendrá una sola salida por día, pero dejamos soporte para escenarios operacionales especiales.')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('lista_asignar', 'Lista para asignar'), ('asignada', 'Asignada'), ('en_ejecucion', 'En ejecución'), ('parcial', 'Parcial'), ('finalizada', 'Finalizada'), ('reprogramada', 'Reprogramada'), ('cancelada', 'Cancelada')], db_index=True, default='borrador', max_length=30)),
                ('origen', models.CharField(choices=[('motor', 'Motor'), ('manual', 'Manual'), ('reprogramacion', 'Reprogramación')], db_index=True, default='motor', max_length=20)),
                ('minutos_viaje_estimados', models.PositiveIntegerField(default=0)),
                ('minutos_trabajo_estimados', models.PositiveIntegerField(default=0)),
                ('minutos_total_estimados', models.PositiveIntegerField(default=0)),
                ('distancia_directa_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('distancia_vial_estimada_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('jornada_extendida', models.BooleanField(default=False)),
                ('exceso_jornada_minutos', models.PositiveIntegerField(default=0)),
                ('puntaje_motor', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('motivo_motor', models.TextField(blank=True, default='')),
                ('bloqueada', models.BooleanField(default=False, help_text='Cuando está activa, futuras recalculaciones del motor diario no pueden modificar automáticamente esta salida.')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_planificacion_diaria_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas_diarias', to='planificacion.batchplanificacionsemanal')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_planificacion_diaria_creadas', to=settings.AUTH_USER_MODEL)),
                ('disponibilidad_cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas_diarias', to='planificacion.disponibilidadcuadrillasemana')),
            ],
            options={
                'verbose_name': 'Salida de planificación diaria',
                'verbose_name_plural': 'Salidas de planificación diaria',
                'ordering': ['fecha', 'disponibilidad_cuadrilla__cuadrilla_operativa__orden', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SitioSalidaPlanificacionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('listo_asignar', 'Listo para asignar'), ('asignado', 'Asignado'), ('en_ejecucion', 'En ejecución'), ('revision', 'En revisión'), ('finalizado', 'Finalizado'), ('no_ejecutado', 'No ejecutado'), ('reprogramado', 'Reprogramado'), ('retirado', 'Retirado'), ('cancelado', 'Cancelado')], db_index=True, default='planificado', max_length=30)),
                ('origen', models.CharField(choices=[('motor', 'Motor'), ('manual', 'Manual'), ('reprogramacion', 'Reprogramación')], db_index=True, default='motor', max_length=20)),
                ('bloqueado', models.BooleanField(default=False, help_text='Impide que una recalculación automática cambie este sitio de salida o fecha.')),
                ('puntaje_motor', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('motivo_motor', models.TextField(blank=True, default='')),
                ('motivo_reprogramacion', models.TextField(blank=True, default='')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitios_salida_diaria_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitios_salida_diaria_creados', to=settings.AUTH_USER_MODEL)),
                ('reprogramado_desde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprogramaciones_generadas', to='planificacion.sitiosalidaplanificaciondiaria')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitios', to='planificacion.salidaplanificaciondiaria')),
                ('sitio_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participaciones_diarias', to='planificacion.sitiobatchsemanal')),
            ],
            options={
                'verbose_name': 'Sitio de salida diaria',
                'verbose_name_plural': 'Sitios de salidas diarias',
                'ordering': ['salida__fecha', 'salida__orden', 'orden', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='salidaplanificaciondiaria',
            index=models.Index(fields=['batch', 'fecha'], name='planificaci_batch_i_be9751_idx'),
        ),
        migrations.AddIndex(
            model_name='salidaplanificaciondiaria',
            index=models.Index(fields=['fecha', 'estado'], name='planificaci_fecha_9585a3_idx'),
        ),
        migrations.AddIndex(
            model_name='salidaplanificaciondiaria',
            index=models.Index(fields=['disponibilidad_cuadrilla', 'fecha'], name='planificaci_disponi_23cc1a_idx'),
        ),
        migrations.AddIndex(
            model_name='salidaplanificaciondiaria',
            index=models.Index(fields=['batch', 'estado'], name='planificaci_batch_i_e36d79_idx'),
        ),
        migrations.AddConstraint(
            model_name='salidaplanificaciondiaria',
            constraint=models.UniqueConstraint(fields=('batch', 'disponibilidad_cuadrilla', 'fecha', 'orden'), name='uq_salida_diaria_batch_cuadrilla_fecha_orden'),
        ),
        migrations.AddIndex(
            model_name='sitiosalidaplanificaciondiaria',
            index=models.Index(fields=['salida', 'estado'], name='planificaci_salida__368a70_idx'),
        ),
        migrations.AddIndex(
            model_name='sitiosalidaplanificaciondiaria',
            index=models.Index(fields=['sitio_batch', 'estado'], name='planificaci_sitio_b_211d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='sitiosalidaplanificaciondiaria',
            index=models.Index(fields=['estado', 'actualizado_en'], name='planificaci_estado_e46162_idx'),
        ),
        migrations.AddConstraint(
            model_name='sitiosalidaplanificaciondiaria',
            constraint=models.UniqueConstraint(fields=('salida', 'sitio_batch'), name='uq_sitio_salida_diaria'),
        ),
    ]
