# Generated by Django 5.2.1 on 2026-08-19 21:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0008_alter_disponibilidadcuadrillasemana_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrioridadPlanificacionDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta'), ('critica', 'Crítica')], db_index=True, default='alta', max_length=20)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cumplida', 'Cumplida'), ('cancelada', 'Cancelada')], db_index=True, default='activa', max_length=20)),
                ('es_ancla', models.BooleanField(default=True, help_text='Si está activo, este sitio define territorialmente la salida diaria. Los demás sitios se buscarán preferentemente alrededor de él.')),
                ('fecha_objetivo', models.DateField(blank=True, db_index=True, help_text='Fecha requerida o preferida para ejecutar el sitio. Vacío significa que el motor puede escoger el mejor día.', null=True)),
                ('fecha_es_obligatoria', models.BooleanField(default=False, help_text='Si está activo, el motor no puede mover el sitio a otra fecha diferente de fecha_objetivo.')),
                ('distancia_preferida_km', models.DecimalField(decimal_places=2, default=20, help_text='Distancia preferida alrededor del sitio ancla para buscar los demás sitios de la salida.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('distancia_maxima_km', models.DecimalField(decimal_places=2, default=40, help_text='Distancia máxima de búsqueda automática alrededor del sitio prioritario antes de considerar una excepción.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('minutos_preferidos', models.PositiveSmallIntegerField(default=30, help_text='Tiempo máximo preferido entre el sitio prioritario y los demás sitios candidatos.')),
                ('minutos_maximos', models.PositiveSmallIntegerField(default=45, help_text='Tiempo máximo tolerado antes de requerir una decisión manual para completar la salida.')),
                ('objetivo_sitios_salida', models.PositiveSmallIntegerField(default=3, help_text='Cantidad objetivo de sitios que debe contener la salida generada alrededor del sitio prioritario.')),
                ('permitir_salida_2_sitios', models.BooleanField(default=True, help_text='Permite cerrar excepcionalmente la salida con dos sitios si no existe un tercer sitio operacionalmente razonable.')),
                ('permitir_salida_1_sitio', models.BooleanField(default=False, help_text='Permite ejecutar únicamente el sitio prioritario. Debe utilizarse solo como última excepción.')),
                ('requiere_confirmacion_excepcion', models.BooleanField(default=True, help_text='Si no existen suficientes sitios dentro de los límites preferidos, el sistema debe pedir confirmación antes de utilizar candidatos más alejados.')),
                ('motivo', models.TextField(blank=True, default='', help_text='Motivo operacional de la prioridad. Ejemplo: solicitud del cliente, acreditación, ventana de acceso o compromiso especial.')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prioridades_diarias_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prioridades_diarias_creadas', to=settings.AUTH_USER_MODEL)),
                ('cuadrilla_obligatoria', models.ForeignKey(blank=True, help_text='Cuadrilla que obligatoriamente debe ejecutar el sitio. Vacío significa que cualquier cuadrilla compatible puede realizarlo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prioridades_diarias_obligatorias', to='planificacion.cuadrillaoperativa')),
                ('sitio_batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prioridad_diaria', to='planificacion.sitiobatchsemanal')),
            ],
            options={
                'verbose_name': 'Prioridad de planificación diaria',
                'verbose_name_plural': 'Prioridades de planificación diaria',
                'ordering': ['-prioridad', 'fecha_objetivo', 'sitio_batch__sitio_planificado__sitio__id_claro', 'id'],
                'indexes': [models.Index(fields=['estado', 'prioridad'], name='planificaci_estado_80bc3d_idx'), models.Index(fields=['fecha_objetivo', 'estado'], name='planificaci_fecha_o_c9da5a_idx'), models.Index(fields=['cuadrilla_obligatoria', 'estado'], name='planificaci_cuadril_b1f84a_idx')],
            },
        ),
    ]
