# Generated by Django 5.2.1 on 2026-08-21 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# ============================================================
# MIGRACIÓN DE DATOS
# ============================================================


def copiar_planificacion_legacy_a_origenes(
    apps,
    schema_editor,
):
    """
    Conserva la procedencia histórica de los batches existentes.

    Antes de esta migración:

        BatchPlanificacionSemanal.planificacion
            = dueño exclusivo del batch.

    Después de esta migración:

        planificacion
            = referencia legacy / mes que originó el batch;

        planificaciones_origen
            = uno o varios meses cuyos sitios participan
              en la misma semana operacional.

    Para los batches existentes copiamos inicialmente:

        planificacion
            ->
        planificaciones_origen

    De esta forma ningún batch histórico queda sin
    procedencia mensual.
    """

    BatchPlanificacionSemanal = apps.get_model(
        "planificacion",
        "BatchPlanificacionSemanal",
    )

    for batch in BatchPlanificacionSemanal.objects.exclude(
        planificacion_id__isnull=True,
    ).iterator():

        batch.planificaciones_origen.add(
            batch.planificacion_id,
        )


def revertir_planificaciones_origen(
    apps,
    schema_editor,
):
    """
    Reversa segura de la migración de datos.

    No modificamos el campo legacy `planificacion`.
    Solamente limpiamos el M2M incorporado por esta migración.
    """

    BatchPlanificacionSemanal = apps.get_model(
        "planificacion",
        "BatchPlanificacionSemanal",
    )

    for batch in BatchPlanificacionSemanal.objects.iterator():

        batch.planificaciones_origen.clear()


class Migration(migrations.Migration):

    dependencies = [
        (
            "planificacion",
            "0009_prioridadplanificaciondiaria",
        ),
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL,
        ),
    ]

    operations = [
        # ====================================================
        # RETIRAR RESTRICCIONES ANTIGUAS
        # ====================================================
        migrations.RemoveConstraint(
            model_name="batchplanificacionsemanal",
            name="uq_batch_semana_planificacion",
        ),
        migrations.RemoveConstraint(
            model_name="configuracionsemana",
            name="uq_semana_planificacion",
        ),
        migrations.RemoveIndex(
            model_name="batchplanificacionsemanal",
            name="planificaci_planifi_349e5d_idx",
        ),
        # ====================================================
        # PROCEDENCIA MULTIMES
        # ====================================================
        migrations.AddField(
            model_name="batchplanificacionsemanal",
            name="planificaciones_origen",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Planificaciones mensuales cuyos sitios "
                    "pueden participar dentro de esta semana "
                    "operacional."
                ),
                related_name="batches_semanales",
                to="planificacion.planificacionmensual",
            ),
        ),
        # ====================================================
        # MIGRAR PROCEDENCIA HISTÓRICA
        # ====================================================
        migrations.RunPython(
            copiar_planificacion_legacy_a_origenes,
            revertir_planificaciones_origen,
        ),
        # ====================================================
        # BATCH -> CONFIGURACIÓN GLOBAL
        # ====================================================
        migrations.AlterField(
            model_name="batchplanificacionsemanal",
            name="configuracion_semana",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="batch",
                to="planificacion.configuracionsemana",
            ),
        ),
        # ====================================================
        # FECHA GLOBAL DEL BATCH
        # ====================================================
        migrations.AlterField(
            model_name="batchplanificacionsemanal",
            name="fecha_inicio",
            field=models.DateField(
                db_index=True,
                help_text="Lunes de la semana ISO objetivo.",
            ),
        ),
        migrations.AlterField(
            model_name="batchplanificacionsemanal",
            name="objetivo_sitios",
            field=models.PositiveIntegerField(
                default=40,
                help_text=(
                    "Cantidad objetivo aproximada de sitios "
                    "activos dentro de la semana."
                ),
            ),
        ),
        # ====================================================
        # PLANIFICACIÓN LEGACY DEL BATCH
        # ====================================================
        migrations.AlterField(
            model_name="batchplanificacionsemanal",
            name="planificacion",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Planificación mensual que originó "
                    "inicialmente el batch. Campo legacy; "
                    "una semana puede actualmente recibir "
                    "sitios de múltiples meses."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="batches_legacy",
                to="planificacion.planificacionmensual",
            ),
        ),
        # ====================================================
        # CONFIGURACIÓN GLOBAL DE SEMANA
        # ====================================================
        migrations.AlterField(
            model_name="configuracionsemana",
            name="fecha_inicio",
            field=models.DateField(
                db_index=True,
                help_text=("Debe corresponder al lunes " "de la semana ISO."),
            ),
        ),
        migrations.AlterField(
            model_name="configuracionsemana",
            name="planificacion",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Relación histórica con el mes que creó "
                    "originalmente la configuración. "
                    "Los servicios nuevos no deben utilizarla "
                    "como dueño exclusivo de la semana."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="semanas_legacy",
                to="planificacion.planificacionmensual",
            ),
        ),
        # ====================================================
        # ÍNDICES
        # ====================================================
        migrations.AddIndex(
            model_name="batchplanificacionsemanal",
            index=models.Index(
                fields=[
                    "estado",
                    "actualizado_en",
                ],
                name="planificaci_estado_5a1fad_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="configuracionsemana",
            index=models.Index(
                fields=[
                    "fecha_inicio",
                ],
                name="planificaci_fecha_i_72d462_idx",
            ),
        ),
        # ====================================================
        # UNICIDAD GLOBAL
        # ====================================================
        migrations.AddConstraint(
            model_name="batchplanificacionsemanal",
            constraint=models.UniqueConstraint(
                fields=("fecha_inicio",),
                name="uq_batch_semana_global",
            ),
        ),
        migrations.AddConstraint(
            model_name="configuracionsemana",
            constraint=models.UniqueConstraint(
                fields=("fecha_inicio",),
                name="uq_configuracion_semana_global",
            ),
        ),
    ]
