# Generated by Django 5.2.1 on 2026-08-24 15:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0010_remove_batchplanificacionsemanal_uq_batch_semana_planificacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadrillaoperativa',
            name='integrantes',
            field=models.ManyToManyField(blank=True, help_text='Usuarios operativos que conforman habitualmente esta cuadrilla.', related_name='cuadrillas_operativas', to=settings.AUTH_USER_MODEL),
        ),
    ]
