# Generated by Django 5.2.1 on 2026-08-26 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0017_sitiomovil_tipo_zona_sitiostablametadata'),
        ('planificacion', '0011_cuadrillaoperativa_integrantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilaImportacionContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fila', models.PositiveIntegerField(db_index=True)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('actualizar', 'Actualizar'), ('sin_cambios', 'Sin cambios'), ('error', 'Error')], db_index=True, max_length=20)),
                ('vinculado', models.BooleanField(db_index=True, default=False)),
                ('vinculo_por', models.CharField(blank=True, default='', max_length=50)),
                ('id_origen', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('nombre_sitio', models.CharField(blank=True, default='', max_length=255)),
                ('propietario', models.CharField(blank=True, default='', max_length=255)),
                ('telefono', models.CharField(blank=True, default='', max_length=255)),
                ('correo', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_informacion', models.DateField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, default='', max_length=255)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('accion', models.TextField(blank=True, default='')),
                ('cambios', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='planificacion.contactositio')),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas_preview', to='planificacion.importacioncontactossitios')),
                ('sitio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='operaciones.sitiomovil')),
            ],
            options={
                'ordering': ['numero_fila', 'id'],
                'indexes': [models.Index(fields=['importacion', 'estado'], name='planificaci_importa_a46c8b_idx'), models.Index(fields=['importacion', 'vinculado'], name='planificaci_importa_6e2566_idx'), models.Index(fields=['importacion', 'numero_fila'], name='planificaci_importa_1fe16f_idx')],
                'constraints': [models.UniqueConstraint(fields=('importacion', 'numero_fila'), name='uq_fila_importacion_contacto')],
            },
        ),
    ]
