# Generated by Django 5.2.1 on 2026-08-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0012_filaimportacioncontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacionmensual',
            name='continuidad_semanal_descartada',
            field=models.JSONField(blank=True, default=list, help_text='Semanas operacionales cuya recomendación de continuidad fue descartada manualmente para esta planificación mensual.'),
        ),
    ]
