# Generated by Django 5.2.1 on 2026-10-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0013_planificacionmensual_continuidad_semanal_descartada'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchplanificacionsemanal',
            name='modo_planificacion',
            field=models.CharField(choices=[('automatico', 'Automático'), ('manual', 'Manual'), ('mixto', 'Mixto')], db_index=True, default='automatico', help_text='Define si la semana se prepara automáticamente, manualmente o combinando selección manual y motor.', max_length=20),
        ),
    ]
