# Generated by Django 5.2.1 on 2025-10-21 16:03

import django.db.models.deletion
import geo_cam.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=geo_cam.models.geo_upload_to, verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('titulo_manual', models.CharField(blank=True, default='', max_length=200, verbose_name='Título (manual)')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('acc', models.FloatField(blank=True, null=True, verbose_name='Precisión GPS (m)')),
                ('client_taken_at', models.DateTimeField(blank=True, help_text='Fecha/hora local del dispositivo al momento de la toma.', null=True, verbose_name='Tomada en (cliente)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_photos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Foto con GPS',
                'verbose_name_plural': 'Fotos con GPS',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='geo_cam_geo_user_id_a1b7dc_idx'), models.Index(fields=['created_at'], name='geo_cam_geo_created_76acb5_idx')],
            },
        ),
    ]
