# Generated by Django 5.2.1 on 2025-11-11 02:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_cam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='geophoto',
            name='geo_cam_geo_user_id_a1b7dc_idx',
        ),
        migrations.AddIndex(
            model_name='geophoto',
            index=models.Index(fields=['user', 'created_at'], name='geo_cam_geo_user_id_8e9d17_idx'),
        ),
    ]
