# Generated by Django 5.2.1 on 2025-12-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_customuser_es_bodeguero_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_notificaciones_activo',
            field=models.BooleanField(default=True, help_text='Si está activo, se enviarán correos de notificación a este usuario.', verbose_name='Correo de notificaciones activo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_activo',
            field=models.BooleanField(default=False, help_text='Si está activo, se enviarán notificaciones vía Telegram.', verbose_name='Telegram activo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID interno del chat de Telegram para enviar notificaciones.', max_length=64, null=True, verbose_name='Chat ID de Telegram'),
        ),
    ]
