# Generated by Django 5.2.1 on 2025-09-03 19:18

import django.core.validators
import operaciones.models
import operaciones.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_serviciocotizado_fecha_aprobacion_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciocotizado',
            name='acta_aceptacion_pdf',
            field=models.FileField(blank=True, max_length=1024, null=True, storage=operaciones.storage_backends.GZWasabiStorage(), upload_to=operaciones.models.upload_to_acta_field, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='serviciocotizado',
            name='documento_compra',
            field=models.CharField(blank=True, help_text='N° de OC/Documento de compra para el acta', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='serviciocotizado',
            name='monto_uf',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto en UF para el acta', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='serviciocotizado',
            name='proyecto_especial',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='serviciocotizado',
            name='reporte_fotografico',
            field=models.FileField(blank=True, max_length=1024, null=True, storage=operaciones.storage_backends.GZWasabiStorage(), upload_to=operaciones.models.upload_to_reporte_field),
        ),
    ]
