# Generated by Django 5.2.1 on 2025-09-03 19:56

import django.db.models.deletion
import operaciones.storage_backends
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_serviciocotizado_acta_aceptacion_pdf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciocotizado',
            name='proyecto_especial',
        ),
        migrations.CreateModel(
            name='SesionFotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('asignado', 'Asignado'), ('en_proceso', 'En proceso'), ('en_revision_supervisor', 'En revisión del supervisor'), ('rechazado_supervisor', 'Rechazado por supervisor'), ('aprobado_supervisor', 'Aprobado por supervisor'), ('rechazado_pm', 'Rechazado por PM'), ('aprobado_pm', 'Aprobado por PM')], default='asignado', max_length=32)),
                ('proyecto_especial', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('servicio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sesion_fotos', to='operaciones.serviciocotizado')),
            ],
        ),
        migrations.CreateModel(
            name='SesionFotoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('asignado', 'Asignado'), ('en_proceso', 'En proceso'), ('en_revision_supervisor', 'En revisión del supervisor'), ('rechazado_supervisor', 'Rechazado por supervisor'), ('aprobado_supervisor', 'Aprobado por supervisor'), ('rechazado_pm', 'Rechazado por PM'), ('aprobado_pm', 'Aprobado por PM')], default='asignado', max_length=32)),
                ('aceptado_en', models.DateTimeField(blank=True, null=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('reintento_habilitado', models.BooleanField(default=False)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='operaciones.sesionfotos')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_fotos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('obligatorio', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('tecnico_sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='operaciones.sesionfototecnico')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(max_length=1024, storage=operaciones.storage_backends.GZWasabiStorage(), upload_to='operaciones/reporte_fotografico/%Y/%m/%d/evidencias/')),
                ('nota', models.TextField(blank=True, default='')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('gps_accuracy_m', models.FloatField(blank=True, null=True)),
                ('client_taken_at', models.DateTimeField(blank=True, null=True)),
                ('tomada_en', models.DateTimeField(auto_now_add=True)),
                ('titulo_manual', models.CharField(blank=True, default='', max_length=200)),
                ('direccion_manual', models.CharField(blank=True, default='', max_length=200)),
                ('requisito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='operaciones.requisitofoto')),
                ('tecnico_sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='operaciones.sesionfototecnico')),
            ],
        ),
    ]
