# Generated by Django 5.2.1 on 2025-09-09 04:15

import operaciones.models
import operaciones.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_remove_serviciocotizado_proyecto_especial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenciafoto',
            name='imagen',
            field=models.FileField(max_length=1024, storage=operaciones.storage_backends.GZWasabiStorage(), upload_to=operaciones.models.upload_to_evidencia),
        ),
    ]
