# Generated by Django 5.2.1 on 2025-09-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_alter_evidenciafoto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciocotizado',
            name='estado',
            field=models.CharField(choices=[('cotizado', 'Cotizado'), ('aprobado_pendiente', 'Aprobada, pendiente por asignar'), ('asignado', 'Asignado'), ('en_progreso', 'En progreso'), ('en_revision_supervisor', 'En revision supervisor'), ('rechazado_supervisor', 'Rechazado por supervisor'), ('aprobado_supervisor', 'Aprobado por supervisor')], default='cotizado', max_length=50),
        ),
    ]
