# Generated by Django 5.2.1 on 2025-09-29 15:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0007_alter_serviciocotizado_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdelantoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mes_aplicado', models.CharField(blank=True, max_length=7, null=True)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adelantos_gz', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DescuentoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('mes_aplicado', models.CharField(blank=True, max_length=7, null=True)),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descuentos_tecnico_gz', to='operaciones.serviciocotizado')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descuentos_gz', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=7)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_pago', 'Pendiente de pago'), ('pagado', 'Pagado'), ('anulado', 'Anulado')], default='borrador', max_length=16)),
                ('monto_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_adelantos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_neto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recibo', models.FileField(blank=True, max_length=512, null=True, upload_to='recibos_liquidacion_gz/')),
                ('pagado_el', models.DateField(blank=True, null=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_mensuales_gz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-mes', 'tecnico_id'],
                'unique_together': {('tecnico', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='ItemLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('servicio', 'Servicio'), ('descuento', 'Descuento'), ('adelanto', 'Adelanto')], max_length=16)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('du', models.CharField(blank=True, default='', max_length=20)),
                ('id_claro', models.CharField(blank=True, default='', max_length=100)),
                ('detalle', models.CharField(blank=True, default='', max_length=255)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_liquidacion_gz', to='operaciones.serviciocotizado')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operaciones.liquidacionmensual')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
