# Generated by Django 5.2.1 on 2025-09-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0008_adelantotecnico_descuentotecnico_liquidacionmensual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descuentotecnico',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='descuentotecnico',
            name='tecnico',
        ),
        migrations.RemoveField(
            model_name='itemliquidacion',
            name='liquidacion',
        ),
        migrations.RemoveField(
            model_name='itemliquidacion',
            name='servicio',
        ),
        migrations.AlterUniqueTogether(
            name='liquidacionmensual',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='liquidacionmensual',
            name='tecnico',
        ),
        migrations.DeleteModel(
            name='AdelantoTecnico',
        ),
        migrations.DeleteModel(
            name='DescuentoTecnico',
        ),
        migrations.DeleteModel(
            name='ItemLiquidacion',
        ),
        migrations.DeleteModel(
            name='LiquidacionMensual',
        ),
    ]
