# Generated by Django 5.2.1 on 2025-09-29 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0009_remove_descuentotecnico_servicio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending_user', 'Pendiente aprobación del técnico'), ('approved_user', 'Aprobado por el técnico'), ('rejected_user', 'Rechazado por el técnico'), ('pending_payment', 'Pendiente de pago'), ('paid', 'Pagado')], db_index=True, default='pending_user', max_length=20)),
                ('reject_reason', models.TextField(blank=True, default='')),
                ('paid_month', models.CharField(blank=True, default='', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', 'technician_id'],
                'indexes': [models.Index(fields=['month', 'status'], name='operaciones_month_137b68_idx'), models.Index(fields=['technician', 'month'], name='operaciones_technic_40956b_idx')],
                'unique_together': {('technician', 'month')},
            },
        ),
    ]
