# Generated by Django 5.2.1 on 2025-09-30 00:15

import django.core.validators
import operaciones.models
import operaciones.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0010_monthlypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlypayment',
            name='receipt',
            field=models.FileField(blank=True, max_length=1024, null=True, storage=operaciones.storage_backends.GZWasabiStorage(), upload_to=operaciones.models.upload_to_payment_receipt, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
