# Generated by Django 5.2.1 on 2025-10-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0011_monthlypayment_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciocotizado',
            name='estado',
            field=models.CharField(choices=[('cotizado', 'Cotizado'), ('aprobado_pendiente', 'Aprobada, pendiente por asignar'), ('asignado', 'Asignado'), ('en_progreso', 'En progreso'), ('en_revision_supervisor', 'En revision supervisor'), ('rechazado_supervisor', 'Rechazado por supervisor'), ('aprobado_supervisor', 'Aprobado por supervisor'), ('ajuste_bono', 'Ajuste: Bono'), ('ajuste_adelanto', 'Ajuste: Adelanto'), ('ajuste_descuento', 'Ajuste: Descuento')], default='cotizado', max_length=50),
        ),
    ]
