# Generated by Django 5.2.1 on 2025-10-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0012_alter_serviciocotizado_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitofoto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
