# Generated by Django 5.2.1 on 2026-08-17 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0016_requisito_norm_cleanup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitiomovil',
            name='tipo_zona',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SitiosTablaMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualizaciones_tabla_sitios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Metadata tabla de sitios',
                'verbose_name_plural': 'Metadata tabla de sitios',
            },
        ),
    ]
