# Generated by Django 5.2.1 on 2026-08-26 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0017_sitiomovil_tipo_zona_sitiostablametadata'),
        ('planificacion', '0013_planificacionmensual_continuidad_semanal_descartada'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciocotizado',
            name='sitio_planificado',
            field=models.ForeignKey(blank=True, help_text='Asignación mensual concreta a la que pertenece este servicio operacional. Permite distinguir ejecuciones históricas repetidas del mismo sitio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_operacionales', to='planificacion.sitioplanificado'),
        ),
    ]
