# Generated by Django 5.2.1 on 2025-11-11 02:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0015_detallesalidamaterial_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidamaterial',
            name='fecha_emision',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha emisión'),
        ),
    ]
