# Generated by Django 5.2.1 on 2026-03-16 18:28

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import logistica.models
import operaciones.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0016_salidamaterial_fecha_emision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('serial', models.CharField(max_length=120, unique=True)),
                ('valor_comercial', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('foto', models.ImageField(blank=True, max_length=1024, null=True, storage=operaciones.storage_backends.GZWasabiStorage(), upload_to=logistica.models.upload_to_herramienta_foto, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('status', models.CharField(choices=[('operativa', 'Operativa'), ('asignada', 'Asignada'), ('danada', 'Dañada'), ('extraviada', 'Extraviada'), ('robada', 'Robada'), ('bodega', 'En bodega')], default='operativa', max_length=20)),
                ('status_justificacion', models.TextField(blank=True, null=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_required', models.BooleanField(default=False, help_text='Si está activo, el usuario debe realizar inventario (subir foto).')),
                ('next_inventory_due', models.DateField(blank=True, null=True)),
                ('last_inventory_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Herramienta',
                'verbose_name_plural': 'Herramientas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HerramientaAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignado_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('comentario_rechazo', models.TextField(blank=True, null=True)),
                ('aceptado_at', models.DateTimeField(blank=True, null=True)),
                ('rechazado_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Asignación de herramienta',
                'verbose_name_plural': 'Asignaciones de herramientas',
                'ordering': ['-asignado_at'],
            },
        ),
        migrations.CreateModel(
            name='HerramientaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(max_length=1024, storage=operaciones.storage_backends.GZWasabiStorage(), upload_to=logistica.models.upload_to_herramienta_inventario, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('revisado_at', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inventario de herramienta',
                'verbose_name_plural': 'Inventarios de herramientas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='archivocaf',
            options={'ordering': ['-fecha_subida', '-id']},
        ),
        migrations.AlterModelOptions(
            name='bodega',
            options={'ordering': ['nombre'], 'verbose_name': 'Bodega', 'verbose_name_plural': 'Bodegas'},
        ),
        migrations.AlterModelOptions(
            name='certificadodigital',
            options={'ordering': ['-fecha_inicio', '-id']},
        ),
        migrations.AlterModelOptions(
            name='detalleingresomaterial',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='detallesalidamaterial',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='foliodisponible',
            options={'ordering': ['folio']},
        ),
        migrations.AlterModelOptions(
            name='ingresomaterial',
            options={'ordering': ['-fecha_ingreso', '-id']},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='salidamaterial',
            options={'ordering': ['-fecha_salida', '-id']},
        ),
        migrations.AddField(
            model_name='bodega',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bodegas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="bodega",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bodega',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='archivocaf',
            name='archivo',
            field=models.FileField(max_length=1024, storage=operaciones.storage_backends.GZWasabiStorage(), upload_to=logistica.models.upload_to_caf, validators=[django.core.validators.FileExtensionValidator(['xml'])], verbose_name='Archivo CAF (.xml)'),
        ),
        migrations.AlterField(
            model_name='archivocaf',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='nombre',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='certificadodigital',
            name='archivo',
            field=models.FileField(max_length=1024, storage=operaciones.storage_backends.GZWasabiStorage(), upload_to=logistica.models.upload_to_certificado, validators=[django.core.validators.FileExtensionValidator(['pfx'])], verbose_name='Archivo .pfx'),
        ),
        migrations.AlterField(
            model_name='ingresomaterial',
            name='archivo_documento',
            field=models.FileField(blank=True, max_length=1024, null=True, storage=operaciones.storage_backends.GZWasabiStorage(), upload_to=logistica.models.upload_to_ingreso_material, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF de respaldo'),
        ),
        migrations.AlterField(
            model_name='material',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor unitario ($)'),
        ),
        migrations.AlterField(
            model_name='salidamaterial',
            name='archivo_pdf',
            field=models.FileField(blank=True, max_length=1024, null=True, storage=operaciones.storage_backends.GZWasabiStorage(), upload_to=logistica.models.upload_to_salida_pdf, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='salidamaterial',
            name='archivo_xml',
            field=models.FileField(blank=True, max_length=1024, null=True, storage=operaciones.storage_backends.GZWasabiStorage(), upload_to=logistica.models.upload_to_salida_xml, validators=[django.core.validators.FileExtensionValidator(['xml'])], verbose_name='XML firmado'),
        ),
        migrations.AlterField(
            model_name='salidamaterial',
            name='tipo_documento',
            field=models.CharField(choices=[('guia', 'Guía de Despacho'), ('factura', 'Factura')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='archivocaf',
            index=models.Index(fields=['tipo_dte', 'estado'], name='logistica_a_tipo_dt_6465ac_idx'),
        ),
        migrations.AddIndex(
            model_name='ingresomaterial',
            index=models.Index(fields=['tipo_documento', 'numero_documento'], name='logistica_i_tipo_do_d2c872_idx'),
        ),
        migrations.AddIndex(
            model_name='ingresomaterial',
            index=models.Index(fields=['bodega', 'fecha_ingreso'], name='logistica_i_bodega__1b5346_idx'),
        ),
        migrations.AddIndex(
            model_name='salidamaterial',
            index=models.Index(fields=['tipo_documento', 'numero_documento'], name='logistica_s_tipo_do_9ab442_idx'),
        ),
        migrations.AddIndex(
            model_name='salidamaterial',
            index=models.Index(fields=['fecha_salida'], name='logistica_s_fecha_s_e021b0_idx'),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas', to='logistica.bodega'),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas_status_cambiado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='herramientaasignacion',
            name='asignado_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='herramientas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='herramientaasignacion',
            name='asignado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas_asignadas_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='herramientaasignacion',
            name='herramienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='logistica.herramienta'),
        ),
        migrations.AddField(
            model_name='herramientainventario',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='logistica.herramientaasignacion'),
        ),
        migrations.AddField(
            model_name='herramientainventario',
            name='herramienta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='logistica.herramienta'),
        ),
        migrations.AddField(
            model_name='herramientainventario',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='herramienta',
            index=models.Index(fields=['status'], name='logistica_h_status_6ab219_idx'),
        ),
        migrations.AddIndex(
            model_name='herramienta',
            index=models.Index(fields=['serial'], name='logistica_h_serial_bdf1ff_idx'),
        ),
        migrations.AddIndex(
            model_name='herramientaasignacion',
            index=models.Index(fields=['active', 'estado'], name='logistica_h_active_c4c22c_idx'),
        ),
        migrations.AddIndex(
            model_name='herramientaasignacion',
            index=models.Index(fields=['asignado_a', 'active'], name='logistica_h_asignad_4cf341_idx'),
        ),
        migrations.AddIndex(
            model_name='herramientainventario',
            index=models.Index(fields=['estado'], name='logistica_h_estado_8ca783_idx'),
        ),
    ]
