# Generated by Django 5.2.1 on 2026-03-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0017_herramienta_herramientaasignacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
