# Generated by Django 5.2.1 on 2026-03-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0018_alter_bodega_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad disponible de esta herramienta/equipo.'),
        ),
    ]
