# Generated by Django 5.2.1 on 2026-03-18 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0019_herramienta_cantidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='herramientaasignacion',
            name='cantidad_devuelta',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herramientaasignacion',
            name='cantidad_entregada',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='herramientaasignacion',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herramientaasignacion',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas_asignaciones_cerradas_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='herramientaasignacion',
            name='comentario_cierre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herramientaasignacion',
            name='justificacion_diferencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herramientaasignacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('terminada', 'Terminada')], default='pendiente', max_length=20),
        ),
        migrations.AddIndex(
            model_name='herramientaasignacion',
            index=models.Index(fields=['herramienta', 'active'], name='logistica_h_herrami_e8d35a_idx'),
        ),
    ]
