# Generated by Django 5.2.1 on 2026-03-18 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0020_herramientaasignacion_cantidad_devuelta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HerramientaAsignacionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('create', 'Creada'), ('update', 'Editada'), ('close', 'Cerrada'), ('reset', 'Reiniciada'), ('delete', 'Eliminada')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cambios', models.JSONField(blank=True, default=dict)),
                ('nota', models.TextField(blank=True, null=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='logistica.herramientaasignacion')),
                ('by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas_asignaciones_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['accion', 'created_at'], name='logistica_h_accion_533b2e_idx'), models.Index(fields=['asignacion', 'created_at'], name='logistica_h_asignac_b0376e_idx')],
            },
        ),
    ]
