# Generated by Django 5.2.1 on 2026-04-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0021_herramientaasignacionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramientaasignacionlog',
            name='accion',
            field=models.CharField(choices=[('create', 'Creada'), ('update', 'Editada'), ('close', 'Cerrada'), ('reset', 'Reiniciada'), ('delete', 'Eliminada'), ('inventario_solicitado', 'Inventario solicitado')], max_length=40),
        ),
    ]
