# Generated by Django 5.2.1 on 2026-09-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting_for_worker', 'Waiting for worker'), ('preparing_dataset', 'Preparing dataset'), ('training', 'Training'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='waiting_for_worker', max_length=32)),
                ('pending_training_at_request', models.PositiveIntegerField(default=0)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('worker_id', models.CharField(blank=True, default='', max_length=128)),
                ('pipeline_stage', models.CharField(blank=True, default='', max_length=64)),
                ('pipeline_message', models.TextField(blank=True, default='')),
                ('quarantined_duplicates', models.PositiveIntegerField(default=0)),
                ('dataset_snapshot', models.JSONField(blank=True, default=dict)),
                ('model_snapshot', models.JSONField(blank=True, default=dict)),
                ('collection_snapshot', models.JSONField(blank=True, default=dict)),
                ('current_epoch', models.PositiveIntegerField(default=0)),
                ('total_epochs', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='scano_train_status_req_idx')],
            },
        ),
    ]
